import tensorflow as tf
import numpy as np
import pickle
from tensorflow.keras.preprocessing.sequence import pad_sequences
 
# Load the trained model
model = tf.keras.models.load_model('intent_model.h5')

# Load the tokenizer
with open('tokenizer.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

# Example new sentences to classify
new_sentences = [
    # 1. Show data requests (Intent 0)
    "Zeige mir bitte die Informationen zu <Name>",
    "Ich möchte den Datensatz von <Name> einsehen",
    "Öffne die Patientenakte von <Name>",
    "Was weißt du über <Name>?",
    "Welche Informationen hast du zu <Name> gespeichert?",
    "Ich will die Daten von <Name> sehen",
    "Lade den Datensatz von <Name> bitte",
    "Kannst du mir <Name>s Profil zeigen?",
    "Zeig mir die Gesundheitsdaten von <Name>",
    "Ich brauche eine Übersicht zu <Name>",
    "Was steht über <Name> im System?",
    "Zeig mir den aktuellen Stand bei <Name>",
    "Was ist zu <Name> hinterlegt?",
    "Ich würde gerne <Name>s Akte einsehen",
    "Welche Details hast du über <Name>?",
    "Gib mir Zugriff auf die Daten von <Name>",
    "Was enthält der Eintrag von <Name>?",
    "Welche Werte sind bei <Name> dokumentiert?",
    "Zeige die gespeicherten Infos zu <Name>",
    "Ich will sehen, was du über <Name> gespeichert hast",
    "Zeige mir alle relevanten Daten zu <Name>",
    "Was enthält die Patientenakte von <Name>?",
    "Welche Infos liegen dir zu <Name> vor?",
    "Bitte zeige mir <Name>s Profilinformationen",
    "Ich möchte alle Daten von <Name> abrufen",
    "Gib mir eine Zusammenfassung der Informationen zu <Name>",
    "Zeige die Akte von <Name> an",
    "Kann ich die Daten von <Name> sehen?",
    "Welche Angaben gibt es zu <Name>?",
    "Zeige die Datenübersicht von <Name>",
    "Ich brauche Details zu <Name>",
    "Öffne die gespeicherten Informationen zu <Name>",
    "Was ist aktuell über <Name> bekannt?",
    "Zeige mir die Profildaten von <Name>",
    "Bitte lade die Informationen von <Name> herunter",
    "Ich will auf die Daten von <Name> zugreifen",
    "Was hast du zu <Name> dokumentiert?",
    "Zeige die medizinischen Daten von <Name>",
    "Gib mir bitte die Übersicht zu <Name>",
    "Ich möchte die Patienteninformationen von <Name> sehen",
    "Welche Daten stehen zu <Name> bereit?",
    "Zeige mir die gespeicherten Daten zu <Name>",
    "Was weißt du über <Name>?",
    "Öffne die Datei mit den Daten von <Name>",
    "Kannst du mir <Name>s Datensatz anzeigen?",
    "Zeige mir die Details zu <Name>",
    "Bitte rufe die Daten von <Name> ab",
    "Ich möchte die Übersicht zu <Name> bekommen",
    "Zeige mir den gespeicherten Datensatz von <Name>",
    "Welche Informationen sind zu <Name> hinterlegt?",
    "Lade bitte die Daten von <Name>",
    "Was gibt es für Informationen über <Name>?",
    "Öffne bitte <Name>s Akte",
    "Zeige alle verfügbaren Daten zu <Name>",
    "Ich will die Akte von <Name> öffnen",
    "Gib mir die Details zu <Name>",
    "Welche Informationen sind bei <Name> gespeichert?",
    "Zeige die Aufzeichnungen zu <Name>",
    "Ich möchte die gespeicherten Daten von <Name> sehen",
    "Kannst du die Daten von <Name> laden?",
    "Bitte zeig mir die Daten von <Name> an",
    "Was für Informationen hast du zu <Name>?",
    "Öffne die Profilinformationen von <Name>",
    "Zeige mir die Akteninformationen von <Name>",
    "Ich möchte die vollständigen Daten zu <Name>",

    # 2. Update data requests (Intent 1)
    "Bitte aktualisiere die Daten von <Name>.",
    "Ich möchte die Informationen zu <Name> ändern.",
    "Kannst du die Angaben zu <Name> updaten?",
    "Aktualisiere bitte das Profil von <Name>.",
    "Füge neue Daten für <Name> hinzu.",
    "Ändere die gespeicherten Informationen von <Name>.",
    "Bitte ergänze die Daten zu <Name>.",
    "Ich will <Name>s Daten bearbeiten.",
    "Lass uns die Daten von <Name> aktualisieren.",
    "Bitte aktualisiere die Patientendaten von <Name>.",
    "Kannst du die Informationen zu <Name> anpassen?",
    "Ich möchte <Name>s Profil aktualisieren.",
    "Ändere bitte die Akte von <Name>.",
    "Füge neue Angaben für <Name> hinzu.",
    "Bitte aktualisiere die gespeicherten Werte von <Name>.",
    "Ich will die Daten von <Name> verändern.",
    "Lade die neuen Informationen für <Name> hoch.",
    "Bitte korrigiere die Daten von <Name>.",
    "Ich möchte die Daten von <Name> ergänzen.",
    "Aktualisiere <Name>s Profildaten.",
    "Bitte passe die Einträge zu <Name> an.",
    "Füge die neuesten Daten für <Name> ein.",
    "Kannst du die Daten von <Name> ändern?",
    "Ich will die Patientendaten von <Name> updaten.",
    "Bitte aktualisiere den Eintrag von <Name>.",
    "Ändere die Informationen, die du zu <Name> hast.",
    "Füge zusätzliche Angaben für <Name> hinzu.",
    "Ich möchte die Akteninformationen von <Name> anpassen.",
    "Bitte aktualisiere die medizinischen Daten von <Name>.",
    "Kannst du die gespeicherten Daten von <Name> korrigieren?",
    "Bitte ergänze die Profilinformationen zu <Name>.",
    "Ich will die Datensätze von <Name> bearbeiten.",
    "Füge neue Details zu <Name> hinzu.",
    "Aktualisiere bitte die Datenbankeinträge für <Name>.",
    "Ich möchte die Angaben von <Name> korrigieren.",
    "Bitte passe <Name>s Patientendaten an.",
    "Ändere die gespeicherten Informationen zu <Name>.",
    "Füge neue Informationen zu <Name> ein.",
    "Bitte aktualisiere die Akte von <Name>.",
    "Kannst du die Profildaten von <Name> aktualisieren?",
    "Ich will die Daten von <Name> korrigieren.",
    "Füge bitte weitere Details zu <Name> hinzu.",
    "Aktualisiere die Einträge für <Name> im System.",
    "Bitte ändere die Patientendaten von <Name>.",
    "Ich möchte neue Informationen zu <Name> hinzufügen.",
    "Kannst du die Angaben zu <Name> aktualisieren?",
    "Bitte überarbeite die Daten von <Name>.",
    "Füge neue Werte für <Name> ein.",
    "Ich möchte die gespeicherten Daten zu <Name> anpassen.",
    "Bitte aktualisiere <Name>s Akte mit den neuesten Daten.",
    "Ändere die Daten, die zu <Name> gespeichert sind.",
    "Füge neue Einträge für <Name> hinzu.",
    "Ich will die Patientendaten von <Name> anpassen.",
    "Bitte korrigiere die Angaben zu <Name>.",
    "Kannst du die Daten von <Name> ergänzen?",
    "Aktualisiere bitte die Informationen zu <Name>.",
    "Ich möchte die Profildaten von <Name> ändern.",
    "Füge neue Informationen zu <Name> hinzu.",
    "Bitte bearbeite die Patientendaten von <Name>.",
    "Kannst du die Daten von <Name> aktualisieren?",
    "Ich will <Name>s Daten ergänzen.",
    "Bitte aktualisiere die gespeicherten Informationen von <Name>.",
    "Füge neue Details in <Name>s Akte ein.",
    "Ich möchte die Daten von <Name> korrigieren.",
    "Bitte ändere die Profilinformationen von <Name>.",
    "Aktualisiere die gespeicherten Daten zu <Name>.",
    "Kannst du die Akte von <Name> updaten?",
    "Ich will die Einträge zu <Name> anpassen.",

    # 3. Insert new data requests (Intent 2)
    "Füge neue Daten zu <Name> ein.",
    "Erstelle einen neuen Eintrag für <Name>.",
    "Bitte registriere neue Informationen für <Name>.",
    "Ich möchte neue Daten zu <Name> hinzufügen.",
    "Lege eine neue Akte für <Name> an.",
    "Trage neue Details zu <Name> ein.",
    "Füge einen neuen Patienten <Name> hinzu.",
    "Eröffne einen neuen Datensatz für <Name>.",
    "Neue Daten für <Name> eintragen.",
    "Erstelle eine neue Patientenakte für <Name>.",
    "Erstelle einen neuen Eintrag für Frau König.",
    "Ich möchte neue Informationen zu Sven hinzufügen.",
    "Trage bitte einen neuen Patienten namens Paul ein.",
    "Füge eine neue Akte für Lisa hinzu.",
    "Neuen Datensatz für Sarah erstellen.",
    "Bitte registriere Laura im System.",
    "Ein neuer Fall für Herr Mayer soll angelegt werden.",
    "Füge einen neuen Kontakt zu deinem System hinzu.",
    "Lege bitte eine neue Person mit dem Namen Emma an.",
    "Erstelle bitte einen neuen Eintrag für <Name>.",
    "Bitte füge einen neuen Datensatz für <Name> hinzu.",
    "Ich möchte eine neue Patientenakte anlegen.",
    "Eröffne bitte einen neuen Fall für <Name>.",
    "Füge neue Patienteninformationen zu <Name> ein.",
    "Bitte lege einen neuen Eintrag für <Name> an.",
    "Erstelle eine neue Akte für <Name>.",
    "Trage einen neuen Datensatz für <Name> ein.",
    "Ich möchte einen neuen Patienten hinzufügen.",
    "Bitte registriere einen neuen Nutzer namens <Name>.",
    "Füge einen neuen Patientenfall hinzu.",
    "Lege eine neue Profilakte für <Name> an.",
    "Erstelle einen neuen Kontakt mit dem Namen <Name>.",
    "Bitte lege neue Daten für <Name> an.",
    "Trage neue Informationen zu <Name> ein.",
    "Erstelle einen neuen Datensatz für einen Patienten.",
    "Füge neue Details für <Name> hinzu.",
    "Ich möchte einen neuen Eintrag anlegen.",
    "Bitte registriere eine neue Person mit dem Namen <Name>.",
    "Lege eine neue Akte für einen Patienten an.",
    "Erstelle einen neuen Fall für <Name>.",
    "Füge einen neuen Patienten mit Namen <Name> hinzu.",
    "Bitte lege einen neuen Patientenfall an.",
    "Trage neue Patientendaten ein.",
    "Erstelle einen neuen Datensatz für <Name> im System.",
    "Ich möchte neue Daten für <Name> erfassen.",
    "Füge bitte einen neuen Eintrag für <Name> ein.",
    "Lege eine neue Akte mit Informationen zu <Name> an.",
    "Bitte registriere einen neuen Nutzer.",
    "Erstelle eine neue Profilseite für <Name>.",
    "Füge eine neue Patientenakte hinzu.",
    "Ich möchte einen neuen Kontakt anlegen.",
    "Lege neue Daten für <Name> im System an.",
    "Bitte erstelle einen neuen Eintrag für einen Patienten.",
    "Füge neue Informationen zu <Name> hinzu.",
    "Erstelle einen neuen Datensatz für einen neuen Patienten.",
    "Bitte trage einen neuen Fall für <Name> ein.",
    "Lege eine neue Patientenakte an.",
    "Füge einen neuen Patientenfall ein.",
    "Ich möchte neue Patientendaten hinzufügen.",
    "Bitte registriere eine neue Akte für <Name>.",
    "Erstelle einen neuen Kontakt mit den Daten von <Name>.",
    "Füge neue Einträge für <Name> hinzu.",
    "Lege eine neue Akte mit den Angaben zu <Name> an.",
    "Bitte erstelle einen neuen Patientenfall.",
    "Ich möchte einen neuen Datensatz anlegen.",
    "Füge einen neuen Patienten mit den Infos von <Name> hinzu.",
    "Lege eine neue Profilakte für <Name> an.",

    # 4. Analyze data requests (Intent 3) 
    "Analysiere die Daten von <Name>.",
    "Bitte mache eine Auswertung für <Name>.",
    "Untersuche die Patientendaten von <Name>.",
    "Gib mir eine Zusammenfassung der Daten von <Name>.",
    "Erstelle einen Bericht über <Name>.",
    "Welche Erkenntnisse gibt es zu <Name>?",
    "Zeige die Analyse der Gesundheitsdaten von <Name>.",
    "Wie ist der Status von <Name> laut Analyse?",
    "Bitte führe eine Datenanalyse für <Name> durch.",
    "Analysiere die Entwicklung von <Name>.",
    "Ich brauche eine Auswertung für <Name>.",
    "Was sagen die Statistiken über <Name> aus?",
    "Gib mir einen Bericht zu <Name>.",
    "Welche Muster erkennst du bei <Name>?",
    "Analysiere bitte die Patientendaten von <Name>.",
    "Erstelle eine Zusammenfassung der Gesundheitsdaten von <Name>.",
    "Wie sieht die Analyse der Daten von <Name> aus?",
    "Untersuche die Trends bei <Name>.",
    "Bitte mach eine Statistik für <Name>.",
    "Gib mir eine Übersicht der Daten von <Name>.",
    "Führe eine Berechnung auf Basis der Daten von <Name> durch.",
    "Welche Entwicklung zeigt <Name> in den letzten Monaten?",
    "Analysiere die Laborwerte von <Name>.",
    "Bitte prüfe die Messdaten von <Name>.",
    "Wie sind die Ergebnisse der Analyse für <Name>?",
    "Gib mir eine Auswertung der Patientendaten von <Name>.",
    "Untersuche die Vitalwerte von <Name>.",
    "Analysiere den Gesundheitszustand von <Name>.",
    "Führe eine statistische Auswertung für <Name> durch.",
    "Bitte zeige mir die Auswertung zu <Name>.",
    "Erstelle einen Bericht zur Datenlage von <Name>.",
    "Was sagt die Analyse der Daten von <Name> aus?",
    "Untersuche die Werte von <Name> auf Auffälligkeiten.",
    "Bitte mache eine Trendanalyse für <Name>.",
    "Wie sind die Laborbefunde von <Name> statistisch zu bewerten?",
    "Gib mir eine detaillierte Auswertung für <Name>.",
    "Analysiere die Entwicklung der Patientendaten von <Name>.",
    "Bitte zeige eine Zusammenfassung der Auswertung für <Name>.",
    "Wie sind die Vitalwerte von <Name> laut Analyse?",
    "Erstelle eine grafische Auswertung für <Name>.",
    "Führe eine Berechnung der Risikofaktoren von <Name> durch.",
    "Bitte analysiere die Medikamentendaten von <Name>.",
    "Untersuche die Blutwerte von <Name>.",
    "Gib mir einen Überblick der Gesundheitsdaten von <Name>.",
    "Analysiere die Beschwerden von <Name> statistisch.",
    "Bitte mache eine Prognose basierend auf den Daten von <Name>.",
    "Erstelle eine Analyse der Krankheitsverläufe von <Name>.",
    "Wie ist die statistische Lage zu <Name>?",
    "Untersuche die Patientendaten auf Trends.",
    "Bitte führe eine Datenanalyse zu <Name> durch.",
    "Gib mir einen Bericht zur Entwicklung von <Name>.",
    "Analysiere die Symptomdaten von <Name>.",
    "Bitte mache eine Zusammenfassung der Gesundheitsdaten von <Name>.",
    "Wie sind die statistischen Auswertungen für <Name>?",
    "Erstelle eine Analyse der Laborwerte von <Name>.",
    "Bitte prüfe die Auswertung der Patientendaten von <Name>.",
    "Führe eine Berechnung der Gesundheitsrisiken für <Name> durch.",
    "Gib mir eine statistische Übersicht der Daten von <Name>.",
    "Analysiere bitte die Vitalzeichen von <Name>.",
    "Bitte erstelle eine Zusammenfassung der Datenanalyse.",
    "Wie sind die Ergebnisse der statistischen Analyse von <Name>?",
    "Untersuche die Patientendaten von <Name> auf Muster.",
    "Gib mir eine Auswertung der Befunde von <Name>.",
    "Analysiere die Gesundheitsentwicklung von <Name>.",
    "Bitte mache eine detaillierte Auswertung der Daten von <Name>.",
    "Erstelle einen Bericht über die medizinischen Daten von <Name>.",
    "Führe eine Analyse der Diagnosedaten von <Name> durch.",
    "Bitte zeige die wichtigsten Erkenntnisse zu <Name>.",
    "Gib mir eine Zusammenfassung der Statistiken von <Name>.",

    # 5. Events/settings requests (Intent 4)
   "Wann ist der nächste Termin von <Name>?",
    "Welche Termine hat <Name> diese Woche?",
    "Gibt es bald wichtige Ereignisse für <Name>?",
    "Zeige die Termine von <Name> an.",
    "Ich möchte die nächsten Arzttermine von <Name> wissen.",
    "Welche geplanten Termine stehen für <Name> an?",
    "Bitte erinnere mich an die Termine von <Name>.",
    "Was ist der nächste Kontrolltermin von <Name>?",
    "Wie sieht der Kalender von <Name> aus?",
    "Gibt es Änderungen bei den Terminen von <Name>?",
    "Welche Einstellungen sind für <Name> aktuell aktiv?",
    "Zeig mir die anstehenden Termine von <Name>.",
    "Wann hat <Name> den nächsten Termin beim Arzt?",
    "Welche Events sind für <Name> geplant?",
    "Bitte zeige alle Termine von <Name> für diesen Monat.",
    "Gibt es neue Termine für <Name>?",
    "Wie sind die Medikationseinstellungen bei <Name>?",
    "Was steht im Kalender von <Name>?",
    "Zeige die System- oder Benutzereinstellungen von <Name>.",
    "Wann sind die nächsten Behandlungstermine von <Name>?",
    "Ich brauche eine Übersicht über die Termine von <Name>.",
    "Welche wichtigen Termine hat <Name> heute?",
    "Gibt es einen Termin für <Name> in den nächsten Tagen?",
    "Zeige mir die nächsten geplanten Termine von <Name>.",
    "Was ist der Zeitplan von <Name> für diese Woche?",
    "Erinnere mich an den nächsten Termin von <Name>.",
    "Welche Termine sind für <Name> im Kalender eingetragen?",
    "Gibt es neue Ereignisse für <Name>?",
    "Wann ist der nächste Zahnarzttermin von <Name>?",
    "Welche Termine stehen für <Name> im nächsten Monat an?",
    "Zeige die aktuellen Einstellungen von <Name>.",
    "Was sind die wichtigsten Termine für <Name>?",
    "Wie ist der Terminplan von <Name>?",
    "Gibt es offene Termine für <Name>?",
    "Bitte zeige alle anstehenden Termine von <Name>.",
    "Wann ist der nächste Impftermin von <Name>?",
    "Welche Arzttermine hat <Name> heute?",
    "Gibt es geplante Untersuchungen für <Name>?",
    "Zeig mir die Kalenderübersicht von <Name>.",
    "Welche Medikationstermine sind für <Name> festgelegt?",
    "Wie lauten die aktuellen Termine für <Name>?",
    "Zeige alle Einstellungen und Termine von <Name> an.",
    "Was steht heute im Kalender von <Name>?",
    "Wann findet der nächste Termin von <Name> statt?",
    "Gibt es Erinnerungen für <Name>?",
    "Bitte zeige die Termine für <Name> an.",
    "Wie sind die Systemeinstellungen von <Name>?",
    "Welche Events stehen für <Name> an?",
    "Wann ist der nächste Check-up von <Name>?",
    "Gibt es wichtige Ereignisse für <Name> in der nächsten Woche?",
    "Zeig mir den Zeitplan von <Name>.",
    "Welche Termine muss ich für <Name> beachten?",
    "Gibt es geplante Therapietermine für <Name>?",
    "Wann ist der nächste Termin im Kalender von <Name>?",
    "Zeige die Termine und Events von <Name>.",
    "Welche Einstellungen hat <Name> bezüglich Terminen?",
    "Gibt es eine Übersicht über die Termine von <Name>?",
    "Was steht als nächstes für <Name> an?",
    "Zeige mir die anstehenden Events von <Name>.",
    "Bitte erinnere mich an alle Termine von <Name>.",
    "Wann sind die nächsten Arztbesuche von <Name>?",
    "Welche Termine sind im System für <Name> hinterlegt?",
    "Gibt es geplante Besuche oder Termine für <Name>?",
    "Zeige die nächste Veranstaltung für <Name>.",
    "Was ist der Zeitplan von <Name> für heute?",
    "Welche wichtigen Termine hat <Name> in diesem Monat?",
    "Wann soll ich <Name> zum Arzt bringen?",
    "Zeig mir alle geplanten Termine von <Name>.",

    # 6. Casual talk / AI Q&A (Intent 5)
    "Hallo, wie geht es dir?",
    "Was kannst du für mich tun?",
    "Erzähl mir einen Witz.",
    "Wie ist das Wetter heute?",
    "Danke für deine Hilfe!",
    "Kannst du mir etwas Interessantes erzählen?",
    "Erzähl mir eine Geschichte.",
    "Wie heißt du?",
    "Was weißt du über Pflege?",
    "Erzähl mir etwas Neues.",
    "Wie geht es dir heute?",
    "Kannst du mir einen lustigen Witz erzählen?",
    "Was kannst du alles tun?",
    "Was ist deine Lieblingsfarbe?",
    "Wie ist das Wetter draußen?",
    "Hast du einen Namen?",
    "Was ist dein Zweck?",
    "Bist du ein echter Mensch?",
    "Erzähl mir was über dich.",
    "Ich finde dich interessant.",
    "Kannst du mir bei meinen Fragen helfen?",
    "Was machst du den ganzen Tag?",
    "Hast du Hobbys?",
    "Erzähl mir einen Fakt über die Welt.",
    "Kannst du singen?",
    "Was ist dein Lieblingsfilm?",
    "Erzähl mir etwas Lustiges.",
    "Magst du Musik?",
    "Was ist das Wichtigste im Leben?",
    "Kannst du tanzen?",
    "Was weißt du über Künstliche Intelligenz?",
    "Erzähl mir einen interessanten Fakt.",
    "Wie alt bist du?",
    "Was ist dein Lieblingsessen?",
    "Kannst du Gedichte schreiben?",
    "Was ist deine Lieblingsfarbe?",
    "Wie kann ich dir vertrauen?",
    "Magst du Sport?",
    "Was macht dich besonders?",
    "Erzähl mir etwas über Technologie.",
    "Was ist deine Lieblingsmusikrichtung?",
    "Kannst du Sprachen lernen?",
    "Wie funktioniert dein Gehirn?",
    "Was ist das Lustigste, das du kennst?",
    "Kannst du mir helfen, kreativ zu sein?",
    "Erzähl mir etwas über das Universum.",
    "Wie fühlst du dich heute?",
    "Hast du Freunde?",
    "Erzähl mir von deinem Tag.",
    "Was sind deine Ziele?",
    "Kannst du tanzen oder singen?",
    "Wie lernst du neue Sachen?",
    "Was würdest du machen, wenn du ein Mensch wärst?",
    "Hast du Lieblingsbücher?",
    "Was ist dein Lieblingssport?",
    "Wie verbringst du deine Freizeit?",
    "Was macht dich glücklich?",
    "Erzähl mir eine interessante Geschichte.",
    "Kannst du programmieren?",
    "Was denkst du über Menschen?",
    "Wie lernst du aus Fehlern?",
    "Magst du Tiere?",
    "Was ist dein Lieblingsurlaubsziel?",
    "Kannst du mir einen Rat geben?",
    "Wie verarbeitest du Informationen?",
    "Erzähl mir einen Witz über Computer.",
    "Wie bist du entstanden?",
    "Was ist das Wichtigste für dich?",
    "Kannst du kreativ sein?",
    "Was möchtest du noch lernen?",

    # Additional without name examples
    "Zeige mir die Termine",
    "Was sind meine aktuellen Einstellungen?"
]

# Convert texts to sequences using tokenizer
sequences = tokenizer.texts_to_sequences(new_sentences)

# Pad sequences to the same length the model expects
max_len = model.input_shape[1]  # input_length from model's first layer
padded_sequences = pad_sequences(sequences, maxlen=max_len, padding='post')

# Predict intents
predictions = model.predict(padded_sequences)

# For example, if you have 6 intents/classes, get the index with max confidence
predicted_classes = np.argmax(predictions, axis=1)

# Map indices to intent labels (replace with your actual labels)
intent_labels = {
    0: "Show data",
    1: "Update data",
    2: "Insert new data",
    3: "Analyze data",
    4: "Events/settings",
    5: "Casual talk"
}

# Print the prediction results
for sentence, pred_class in zip(new_sentences, predicted_classes):
    print(f"Sentence: '{sentence}' --> Predicted intent: {intent_labels.get(pred_class, 'Unknown')}")